version: '3.9'

services:
  postgres_db_test:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    ports:
    - '8000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v6LU2ysixQqihxon
      POSTGRES_DB: postgres_db
    volumes:
    - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local